name: Main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      COCKPIT_API_URL: ${{secrets.COCKPIT_API_URL}}
      COCKPIT_API_TOKEN: ${{secrets.COCKPIT_API_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.elm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json', '**/elm.json') }}
      - uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/1e9c7c0203be.tar.gz
      - uses: cachix/cachix-action@v12
        with:
          name: marco-daniels
          authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
      - name: Build Website
        run: nix-shell buildWebsite.nix --run "buildWebsite"
      - name: Sync Website
        run: aws s3 sync ./dist s3://${{secrets.AWS_S3_BUCKET}}
      - name: Build Preview
        run: nix-build buildPreview.nix
      - name: Sync Preview
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: result/preview