name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      COCKPIT_API_URL: ${{secrets.COCKPIT_API_URL}}
      COCKPIT_API_TOKEN: ${{secrets.COCKPIT_API_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.elm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json', '**/elm.json') }}
      - uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/fc541b860a28.tar.gz
      - uses: cachix/cachix-action@v12
        with:
          name: marco-daniels
          authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
      - name: Build Website
        run: nix-shell buildWebsite.nix --run "buildWebsite"