name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: https://github.com/NixOS/nixpkgs/archive/30daa988f10.tar.gz
      - uses: cachix/cachix-action@v10
        with:
          name: marco-daniels
          authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
      - run: nix-shell --run "yarn"
      - run: nix-shell --run "yarn build"