name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      COCKPIT_API_URL: ${{secrets.COCKPIT_API_URL}}
      COCKPIT_API_TOKEN: ${{secrets.COCKPIT_API_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.elm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json', '**/elm.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Build Application
        run: yarn build